CREATE TABLE IF NOT EXISTS mgmtTenantStatus (
    tenant_id varchar(200) PRIMARY KEY,
    DATASET INTEGER,
    MODULE INTEGER,
    IMAGE INTEGER,
    WORKFLOW INTEGER,
    AUTOML INTEGER,
    NOTEBOOK INTEGER,
    MODELGROUP INTEGER,
    SCORECARD INTEGER,
    CPU DOUBLE PRECISION,
    MEM DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN mgmtTenantStatus.tenant_id IS '租户id';
COMMENT ON COLUMN mgmtTenantStatus.DATASET IS '数据集';
COMMENT ON COLUMN mgmtTenantStatus.MODULE IS '算子数量';
COMMENT ON COLUMN mgmtTenantStatus.IMAGE IS '环境数量';
COMMENT ON COLUMN mgmtTenantStatus.WORKFLOW IS '工作流数量';
COMMENT ON COLUMN mgmtTenantStatus.AUTOML IS '自动建模数量';
COMMENT ON COLUMN mgmtTenantStatus.NOTEBOOK IS '探索空间数量';
COMMENT ON COLUMN mgmtTenantStatus.MODELGROUP IS '模型数量';
COMMENT ON COLUMN mgmtTenantStatus.SCORECARD IS '评分卡数量';
COMMENT ON COLUMN mgmtTenantStatus.CPU IS 'cpu数量';
COMMENT ON COLUMN mgmtTenantStatus.MEM IS 'mem数量';